{% set name = "trufflehogregexes" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/truffleHogRegexes-{{ version }}.tar.gz
  sha256: b81dfc60c86c1e353f436a0e201fd88edb72d5a574615a7858485c59edf32405

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.11

test:
  imports:
    - truffleHogRegexes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dxa4481/truffleHogRegexes
  summary: These regexes power truffleHog.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
